# Generated by Django 3.0.4 on 2020-03-28 08:16

from django.db import migrations, models
import photosRestApi.photos.models
import photosRestApi.photos.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200328_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=photosRestApi.photos.storage_backends.PublicMediaStorage(), upload_to=photosRestApi.photos.models.get_file_path),
        ),
    ]
