# Generated by Django 3.0.4 on 2020-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20200328_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.TextField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED')], default='0'),
        ),
    ]
