# Generated by Django 3.0.4 on 2020-03-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20200328_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.TextField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED')], default='DRAFT'),
        ),
    ]
